# Generated by Django 5.1.7 on 2025-03-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
